/* ============================================================
   SESSION CREDENTIALS — the two secrets a browser holds.

   Both exist because of §9 of the review, and they are different
   kinds of thing, which is why they live in one small file
   together rather than being scattered into the hooks that use
   them.

   THE WARDEN'S TOKEN authorises `?role=host`. It is generated by
   the server, printed in the terminal, and served over /net/info
   *only to loopback* — so the host tab on the same machine picks
   it up silently and a phone on the wifi cannot ask for it. A
   Warden running the deck from another device types it once.

   THE PLAYER'S RESUME KEY is the opposite shape. The browser
   generates it, the server never publishes it, and its only job
   is to let a phone that slept through a scene come back as the
   same player. It replaces the old client-supplied `clientId`,
   which was broadcast to every phone in the roster and could
   therefore be replayed by anyone who read it — see §9.2.

   The distinction worth holding onto: the token proves a *role*,
   the resume key proves *continuity*. Neither is a password and
   neither protects against someone standing behind you. This is
   still a LAN tool for a table of friends; it is just no longer
   one where the friend with a browser console can end the game.
   ============================================================ */

const TOKEN_KEY = "ms:hosttoken";
const RESUME_KEY = "ms:resume";

/* localStorage throws rather than returns null in a few real
   configurations — Safari private browsing historically, and any
   embedded webview with storage disabled. A Warden whose browser
   is in that state should get a session that works and forgets
   itself, not a white screen. */
const store = {
  get(k) { try { return localStorage.getItem(k); } catch { return null; } },
  set(k, v) { try { localStorage.setItem(k, v); } catch { /* ephemeral */ } },
  clear(k) { try { localStorage.removeItem(k); } catch { /* ignore */ } },
};

/** 128 bits, base36. Long enough that guessing is not a strategy,
    short enough to sit in localStorage without comment. */
export function newResumeKey() {
  const buf = new Uint8Array(16);
  if (globalThis.crypto && globalThis.crypto.getRandomValues) {
    globalThis.crypto.getRandomValues(buf);
  } else {
    // Node under test, or a browser old enough that it will not be
    // running this app anyway. Never reached at a real table.
    for (let i = 0; i < buf.length; i++) buf[i] = Math.floor(Math.random() * 256);
  }
  return Array.from(buf, (b) => b.toString(36).padStart(2, "0")).join("");
}

/** This phone's resume key, generated once and kept. */
export function resumeKey() {
  let k = store.get(RESUME_KEY);
  if (!k || k.length < 8) { k = newResumeKey(); store.set(RESUME_KEY, k); }
  return k;
}

/** Deliberately available: "this phone is now a different player"
    is a real thing that happens when a handset is passed on. */
export function forgetResumeKey() { store.clear(RESUME_KEY); }

/* ---------------- the Warden's token ---------------- */

export const savedHostToken = () => store.get(TOKEN_KEY) || "";
export const rememberHostToken = (t) => (t ? store.set(TOKEN_KEY, t) : store.clear(TOKEN_KEY));
export const forgetHostToken = () => store.clear(TOKEN_KEY);

/**
 * Work out what token the host tab should connect with.
 *
 * Order is deliberate:
 *   1. `?token=` in the URL — an explicit instruction beats
 *      anything remembered, and it is how a Warden moves the deck
 *      to a tablet by sending themselves a link.
 *   2. /net/info — present only when we are on the same machine
 *      as the server, which is the ordinary case and the one that
 *      should require no thought at all.
 *   3. Whatever we were given last time.
 *
 * Returns { token, required, source }. `required: false` means the
 * server is running OPEN_HOST and the box should not be shown.
 */
export async function resolveHostToken({ fetchImpl, search } = {}) {
  const f = fetchImpl || (typeof fetch === "function" ? fetch : null);
  const qs = new URLSearchParams(
    search != null ? search : (typeof location !== "undefined" ? location.search : "")
  );

  const fromUrl = qs.get("token");
  if (fromUrl) {
    rememberHostToken(fromUrl);
    return { token: fromUrl, required: true, source: "url" };
  }

  if (f) {
    try {
      const res = await f("/net/info", { cache: "no-store" });
      if (res && res.ok) {
        const info = await res.json();
        if (info && info.tokenRequired === false) return { token: "", required: false, source: "open" };
        if (info && info.token) {
          rememberHostToken(info.token);
          return { token: info.token, required: true, source: "local" };
        }
      }
    } catch { /* served from a build with no relay behind it */ }
  }

  const saved = savedHostToken();
  return { token: saved, required: true, source: saved ? "saved" : "none" };
}
