/* ============================================================
   SOUND — synthesised, not sampled.

   The engine's one hard promise is that it runs offline with no
   network call and no assets to fetch. Shipping a folder of
   ambience .oggs would break that and add megabytes; so every
   sound here is generated by WebAudio at runtime from noise and
   oscillators. The whole file weighs nothing.

   What that buys, per room tag:
     industrial  low rumble + irregular metal stress
     medical     hum + a slow, sterile beep
     derelict    wind-through-structure, no machinery at all
     vacuum      almost nothing: filtered breath and your own pulse
     bridge      electrical hum + soft telemetry chirps
     organic     wet low-frequency movement

   Plus three one-shots that matter: the countdown alarm, the
   Panic stinger, and the dice settle click.

   Nothing autoplays. Browsers require a gesture before audio can
   start, and so does common decency, so the context is created
   lazily on the first explicit unmute.
   ============================================================ */

let ctx = null;
let master = null;
let enabled = false;
let currentBed = null;
let beds = {};

const listeners = new Set();
const notify = () => listeners.forEach((fn) => fn({ enabled, bed: currentBed }));

function ensureContext() {
  if (ctx) return ctx;
  const AC = typeof window !== "undefined" && (window.AudioContext || window.webkitAudioContext);
  if (!AC) return null;
  ctx = new AC();
  master = ctx.createGain();
  master.gain.value = 0.0;
  master.connect(ctx.destination);
  return ctx;
}

/* ---------------- primitives ---------------- */

function noiseBuffer(seconds = 2) {
  const len = Math.floor(ctx.sampleRate * seconds);
  const buf = ctx.createBuffer(1, len, ctx.sampleRate);
  const data = buf.getChannelData(0);
  // Brown-ish noise: gentler and more "room" than white.
  let last = 0;
  for (let i = 0; i < len; i++) {
    const white = Math.random() * 2 - 1;
    last = (last + 0.02 * white) / 1.02;
    data[i] = last * 3.5;
  }
  return buf;
}

function makeNoise({ type = "lowpass", freq = 400, q = 0.7, gain = 0.1 }) {
  const src = ctx.createBufferSource();
  src.buffer = noiseBuffer(3);
  src.loop = true;
  const filter = ctx.createBiquadFilter();
  filter.type = type;
  filter.frequency.value = freq;
  filter.Q.value = q;
  const g = ctx.createGain();
  g.gain.value = gain;
  src.connect(filter).connect(g);
  src.start();
  return { src, filter, gain: g, out: g };
}

function makeDrone({ freq = 55, type = "sine", gain = 0.06, detune = 0 }) {
  const osc = ctx.createOscillator();
  osc.type = type;
  osc.frequency.value = freq;
  osc.detune.value = detune;
  const g = ctx.createGain();
  g.gain.value = gain;
  osc.connect(g);
  osc.start();
  return { osc, gain: g, out: g };
}

/** A single tone with an envelope. Used for every one-shot. */
function blip({ freq = 440, dur = 0.12, type = "sine", gain = 0.2, sweepTo = null, delay = 0 }) {
  if (!ctx || !enabled) return;
  const t = ctx.currentTime + delay;
  const osc = ctx.createOscillator();
  osc.type = type;
  osc.frequency.setValueAtTime(freq, t);
  if (sweepTo != null) osc.frequency.exponentialRampToValueAtTime(Math.max(1, sweepTo), t + dur);
  const g = ctx.createGain();
  g.gain.setValueAtTime(0.0001, t);
  g.gain.exponentialRampToValueAtTime(gain, t + 0.01);
  g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
  osc.connect(g).connect(master);
  osc.start(t);
  osc.stop(t + dur + 0.05);
}

/* ---------------- ambience beds ---------------- */

const BEDS = {
  industrial(bus) {
    const rumble = makeDrone({ freq: 42, type: "sine", gain: 0.10 });
    const air = makeNoise({ freq: 260, gain: 0.05 });
    const hum = makeDrone({ freq: 84, type: "triangle", gain: 0.025 });
    [rumble, air, hum].forEach((n) => n.out.connect(bus));
    // Irregular metal stress. Not a rhythm — a rhythm is comforting.
    const tick = setInterval(() => {
      if (!enabled) return;
      blip({ freq: 90 + Math.random() * 200, dur: 0.09, type: "square", gain: 0.035 });
    }, 5200 + Math.random() * 6000);
    return { nodes: [rumble, air, hum], timers: [tick] };
  },

  medical(bus) {
    const hum = makeDrone({ freq: 120, type: "sine", gain: 0.035 });
    const air = makeNoise({ freq: 900, gain: 0.02 });
    [hum, air].forEach((n) => n.out.connect(bus));
    const beep = setInterval(() => {
      if (!enabled) return;
      blip({ freq: 1180, dur: 0.06, type: "sine", gain: 0.05 });
    }, 4300);
    return { nodes: [hum, air], timers: [beep] };
  },

  derelict(bus) {
    // No machinery at all. That absence is the sound design.
    const wind = makeNoise({ freq: 180, q: 1.4, gain: 0.075 });
    const sub = makeDrone({ freq: 31, type: "sine", gain: 0.05 });
    [wind, sub].forEach((n) => n.out.connect(bus));
    // Slow filter drift so the room seems to breathe.
    const drift = setInterval(() => {
      if (!ctx) return;
      wind.filter.frequency.linearRampToValueAtTime(120 + Math.random() * 220, ctx.currentTime + 6);
    }, 6000);
    const groan = setInterval(() => {
      if (!enabled) return;
      blip({ freq: 70, sweepTo: 44, dur: 1.6, type: "sine", gain: 0.05 });
    }, 17000 + Math.random() * 12000);
    return { nodes: [wind, sub], timers: [drift, groan] };
  },

  vacuum(bus) {
    const sub = makeDrone({ freq: 26, type: "sine", gain: 0.055 });
    const breath = makeNoise({ freq: 520, q: 2.2, gain: 0.03 });
    [sub, breath].forEach((n) => n.out.connect(bus));
    // Suit breathing: the loudest thing out here is you.
    const cycle = setInterval(() => {
      if (!ctx || !enabled) return;
      const t = ctx.currentTime;
      breath.gain.gain.cancelScheduledValues(t);
      breath.gain.gain.linearRampToValueAtTime(0.075, t + 1.5);
      breath.gain.gain.linearRampToValueAtTime(0.018, t + 3.6);
    }, 4000);
    return { nodes: [sub, breath], timers: [cycle] };
  },

  bridge(bus) {
    const hum = makeDrone({ freq: 100, type: "sawtooth", gain: 0.018 });
    const air = makeNoise({ freq: 700, gain: 0.025 });
    [hum, air].forEach((n) => n.out.connect(bus));
    const chirp = setInterval(() => {
      if (!enabled) return;
      blip({ freq: 720 + Math.random() * 900, dur: 0.045, type: "square", gain: 0.028 });
    }, 2600);
    return { nodes: [hum, air], timers: [chirp] };
  },

  organic(bus) {
    const sub = makeDrone({ freq: 36, type: "sine", gain: 0.09 });
    const wet = makeNoise({ freq: 300, q: 3.5, gain: 0.045 });
    [sub, wet].forEach((n) => n.out.connect(bus));
    const move = setInterval(() => {
      if (!ctx || !enabled) return;
      wet.filter.frequency.linearRampToValueAtTime(160 + Math.random() * 500, ctx.currentTime + 2.2);
      if (Math.random() < 0.4) blip({ freq: 55, sweepTo: 38, dur: 0.9, type: "sine", gain: 0.045 });
    }, 3400);
    return { nodes: [sub, wet], timers: [move] };
  },

  quiet(bus) {
    const sub = makeDrone({ freq: 48, type: "sine", gain: 0.03 });
    sub.out.connect(bus);
    return { nodes: [sub], timers: [] };
  },
};

/** Room tags -> bed. First match wins; order is deliberate. */
const TAG_MAP = [
  [["vacuum", "eva", "airless", "0g", "zero-g"], "vacuum"],
  [["organic", "flesh", "hive", "growth", "infested"], "organic"],
  [["medical", "medbay", "lab", "clinic", "science"], "medical"],
  [["bridge", "cockpit", "command", "computer", "control"], "bridge"],
  [["derelict", "abandoned", "ruin", "dark", "empty", "wreck"], "derelict"],
  [["industrial", "engine", "cargo", "reactor", "machine", "mining", "hangar"], "industrial"],
];

export function bedForTags(tags = []) {
  const lower = tags.map((t) => String(t).toLowerCase());
  for (const [keys, bed] of TAG_MAP) {
    if (lower.some((t) => keys.some((k) => t.includes(k)))) return bed;
  }
  return "quiet";
}

/* ---------------- public api ---------------- */

export function setEnabled(on) {
  if (on && !ensureContext()) return false;
  enabled = !!on;
  if (enabled && ctx.state === "suspended") ctx.resume();
  if (master) {
    master.gain.cancelScheduledValues(ctx.currentTime);
    master.gain.linearRampToValueAtTime(enabled ? 0.85 : 0.0, ctx.currentTime + 0.4);
  }
  if (!enabled) stopBed();
  notify();
  return enabled;
}

export const isEnabled = () => enabled;
export const subscribe = (fn) => { listeners.add(fn); return () => listeners.delete(fn); };

/* ============================================================
   WHO IS ALLOWED TO MAKE A NOISE

   Proposed as an invariant: THE TABLE SCREEN OWNS AUDIO, THE
   PHONES OWN HAPTICS.

   Six phones each firing the Panic stinger is not atmosphere, it
   is six tinny speakers a beat apart from each other in a room
   that also has a television in it. The TV has the only good
   speaker present and it is the one device nobody is holding.

   `playForKind` is the table-wide channel — a room's event, heard
   by everybody — and it is silenced outright in phone role. There
   is no setting for this because there is no configuration in
   which the right answer is "all of them at once".

   `playCue` is NOT silenced, and the distinction is the whole
   point of the rule rather than an exception to it. A cue is a
   sound placed in ONE hand deliberately, by a Warden, and the
   file it lives in describes it as "a sound in this hand and no
   other". That is a private channel, and it survives.

   `setRole` is called once per client, at the top. Nothing else
   reads `role`. ============================================================ */
let role = "table";

/** "table" (a shared screen) or "phone" (somebody's handset). */
export function setRole(next) {
  role = next === "phone" ? "phone" : "table";
  /* A phone that had sound on because it was once a table screen
     in the same tab is a phone that will surprise its owner. */
  if (role === "phone" && enabled) setEnabled(false);
  return role;
}
export const isTable = () => role === "table";

/** Crossfade to the bed for a room. No-op if it is already playing. */
export function playBed(name) {
  if (!enabled || !ctx) return;
  const bed = BEDS[name] ? name : "quiet";
  if (currentBed === bed) return;
  stopBed();

  const bus = ctx.createGain();
  bus.gain.value = 0.0001;
  bus.connect(master);
  const built = BEDS[bed](bus);
  bus.gain.exponentialRampToValueAtTime(1, ctx.currentTime + 2.2);

  beds = { bus, ...built };
  currentBed = bed;
  notify();
}

export function stopBed() {
  if (!beds || !beds.bus) { currentBed = null; return; }
  const { bus, nodes = [], timers = [] } = beds;
  timers.forEach(clearInterval);
  const t = ctx.currentTime;
  bus.gain.cancelScheduledValues(t);
  bus.gain.exponentialRampToValueAtTime(0.0001, t + 0.8);
  setTimeout(() => {
    nodes.forEach((n) => {
      try { if (n.src) n.src.stop(); if (n.osc) n.osc.stop(); } catch { /* already stopped */ }
    });
    try { bus.disconnect(); } catch { /* gone */ }
  }, 1000);
  beds = {};
  currentBed = null;
}

/* ---------------- one-shots ---------------- */

export const sfx = {
  /** Dice settling. Two clicks, because two dice. */
  dieLand(which = "tens") {
    blip({ freq: which === "tens" ? 320 : 420, dur: 0.05, type: "square", gain: 0.09 });
    blip({ freq: which === "tens" ? 180 : 240, dur: 0.07, type: "triangle", gain: 0.06, delay: 0.015 });
  },

  success() { blip({ freq: 660, dur: 0.09, type: "sine", gain: 0.09 }); },
  failure() { blip({ freq: 180, sweepTo: 120, dur: 0.22, type: "sine", gain: 0.10 }); },
  critical() {
    blip({ freq: 880, dur: 0.07, type: "square", gain: 0.10 });
    blip({ freq: 1320, dur: 0.10, type: "square", gain: 0.08, delay: 0.07 });
  },

  /** Panic. A held minor second, which the ear refuses to resolve. */
  panic() {
    if (!enabled || !ctx) return;
    blip({ freq: 220, dur: 1.9, type: "sawtooth", gain: 0.075 });
    blip({ freq: 233, dur: 1.9, type: "sawtooth", gain: 0.075 });
    blip({ freq: 55, sweepTo: 40, dur: 2.4, type: "sine", gain: 0.11 });
  },

  /** Countdown alarm. Urgency scales with how little time is left. */
  alarm(urgency = 0) {
    if (!enabled || !ctx) return;
    const n = urgency > 0.7 ? 3 : urgency > 0.35 ? 2 : 1;
    for (let i = 0; i < n; i++) {
      blip({ freq: 740, dur: 0.13, type: "square", gain: 0.11, delay: i * 0.19 });
      blip({ freq: 560, dur: 0.13, type: "square", gain: 0.09, delay: i * 0.19 + 0.09 });
    }
  },

  damage() { blip({ freq: 140, sweepTo: 60, dur: 0.3, type: "sawtooth", gain: 0.12 }); },
  death() { blip({ freq: 110, sweepTo: 30, dur: 2.6, type: "sine", gain: 0.14 }); },
  item() { blip({ freq: 520, dur: 0.05, type: "triangle", gain: 0.07 }); },
  door() { blip({ freq: 95, sweepTo: 150, dur: 0.28, type: "sawtooth", gain: 0.07 }); },

  /** Ship hull impact. Felt more than heard. */
  hullHit() {
    blip({ freq: 70, sweepTo: 34, dur: 0.7, type: "sine", gain: 0.16 });
    blip({ freq: 200, dur: 0.14, type: "sawtooth", gain: 0.06 });
  },

  /* ---------------- the private cues ----------------
     These exist to be sent to one phone. They are deliberately
     ordinary sounds — a knock, a breath, a scrape — because the
     horror is not the sound, it is that nobody else heard it. */

  /** Three knocks, close, on the other side of something. Slightly
      uneven spacing: a metronome is comforting and a person is not. */
  knock() {
    blip({ freq: 96, sweepTo: 62, dur: 0.16, type: "sine", gain: 0.17 });
    blip({ freq: 92, sweepTo: 58, dur: 0.16, type: "sine", gain: 0.15, delay: 0.34 });
    blip({ freq: 99, sweepTo: 60, dur: 0.18, type: "sine", gain: 0.16, delay: 0.63 });
  },

  /** Someone else breathing on your channel. Two cycles, no source. */
  breath() {
    if (!enabled || !ctx) return;
    const n = makeNoise({ type: "bandpass", freq: 480, q: 2.6, gain: 0.0001 });
    n.out.connect(master);
    const t = ctx.currentTime;
    for (let i = 0; i < 2; i++) {
      const at = t + i * 2.2;
      n.gain.gain.linearRampToValueAtTime(0.085, at + 0.9);
      n.gain.gain.linearRampToValueAtTime(0.006, at + 2.0);
    }
    setTimeout(() => { try { n.src.stop(); } catch { /* already stopped */ } }, 4800);
  },

  /** Metal moving slowly where nothing should be moving. */
  scrape() {
    if (!enabled || !ctx) return;
    const n = makeNoise({ type: "bandpass", freq: 1400, q: 7, gain: 0.05 });
    n.out.connect(master);
    const t = ctx.currentTime;
    n.filter.frequency.setValueAtTime(1500, t);
    n.filter.frequency.linearRampToValueAtTime(420, t + 1.5);
    n.gain.gain.linearRampToValueAtTime(0.0001, t + 1.7);
    setTimeout(() => { try { n.src.stop(); } catch { /* already stopped */ } }, 2000);
  },

  /** Your own pulse, suddenly audible. Sits just under the beat you
      can consciously count, which is what makes it unpleasant. */
  heartbeat() {
    for (let i = 0; i < 4; i++) {
      blip({ freq: 58, sweepTo: 40, dur: 0.13, type: "sine", gain: 0.15, delay: i * 0.86 });
      blip({ freq: 52, sweepTo: 36, dur: 0.16, type: "sine", gain: 0.11, delay: i * 0.86 + 0.21 });
    }
  },
};

/** Cue ids (protocol SOUND_CUES) -> one-shots. Kept here so the wire
    only ever carries a name and never a description of a sound. */
const CUES = {
  knock: () => sfx.knock(),
  breath: () => sfx.breath(),
  scrape: () => sfx.scrape(),
  alarm: () => sfx.alarm(1),
  heartbeat: () => sfx.heartbeat(),
};

/**
 * Play a cue the Warden addressed to this phone.
 *
 * Sound is off by default and browsers require a gesture before audio
 * can start — but a player receiving this has been tapping buttons for
 * an hour, so the gesture requirement is long since satisfied and the
 * context will open. We therefore turn sound on for them rather than
 * dropping the cue: a private noise the Warden aimed at one person is
 * not ambience they opted out of, it is addressed to them.
 *
 * Returns whether it actually made a sound, so the caller can fall
 * back to the vibration and the card alone.
 */
export function playCue(name) {
  const fn = CUES[name];
  if (!fn) return false;
  if (!enabled && !setEnabled(true)) return false;
  fn();
  return true;
}

/** Feed kinds -> one-shots, so narration and audio stay in step. */
export function playForKind(kind) {
  /* The shared-screen channel. Silent on a handset by rule — see
     setRole. The phone still buzzes: haptics.js is untouched. */
  if (role !== "table") return;
  if (!enabled) return;
  switch (kind) {
    case "panic": return sfx.panic();
    case "dmg": return sfx.damage();
    case "horror": return sfx.death();
    case "item": return sfx.item();
    case "rollgood": return sfx.success();
    case "rollbad": return sfx.failure();
    default: return undefined;
  }
}

export default {
  setEnabled, isEnabled, playBed, stopBed, sfx, bedForTags,
  playForKind, playCue, subscribe, setRole, isTable,
};
